### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by scopatz**
This PR includes and cleans up #7 and should make it work.  CC @mingwandroid

### CODE REVIEW

**Comment by mingwandroid** [comment]
Cool. Where'd you get my patches from? I cannot remember this stuff :-)

**Comment by scopatz** [comment]
They were just in your PR :)

**Comment by mingwandroid** [comment]
Nice. Thanks for taking this on.

**Comment by mingwandroid** [comment]
Looking at the AppVeyor logs it seems to be using GCC to do the compilation when we want it to use Visual Studio. I'll try to take another look at this tomorrow.

**Comment by scopatz** [comment]
Ahh yeah it wasn't configuring with Visual Studio. Is there any reason why we shouldn't just use gcc?

**Comment by mingwandroid** [comment]
Yeah, for best binary compatibility it is cleaner to link to only one Microsoft C Runtime (see tonight's discussion on this topic: https://github.com/conda-forge/conda-forge.github.io/issues/460, but fair warning, it's long and gets a bit heated).

**Comment by isuruf** [comment]
You might want to have a look at a CMake build here https://github.com/Microsoft/vcpkg/tree/master/ports/libffi (It's not portable like other CMake projects, but should work if you want to use MSVC)

**Pull request closed without merging**
