### PR TITLE
more lib64 fixes

### PR DESCRIPTION
**Pull request by scopatz**
This does a better job of fixing the problem.  Some locations were missed before, including in the pkgconfig.

### CODE REVIEW

**Comment by scopatz** [comment]
@stefan-balke @jakirkham @ocefpaf @pelson

**Comment by scopatz** [comment]
This is again blocking my progress on glibmm

**Comment by scopatz** [comment]
looks like it passes

**Comment by stefan-balke** [comment]
> This is again blocking my progress on glibmm

Hey man,
please stop pushing your stuff–I think a reminder after a day is fine, but not after 30 minutes...

**Comment by scopatz** [comment]
@stefan-balke - Thanks for maintaining this, but you don't need to be the only one. I am  happy to help.  Sorry if I am pushy about this, but this is on my critical path.  I am trying to buy-in to the conda-forge model, but I can see how once something makes it to a feedstock there can be problems with too few maintainers.  Maybe this is something for us to consider

**Comment by scopatz** [comment]
Right now not that many folks have push access to a repo once it is a feedstock.

**Comment by jakirkham** [comment]
If I can make a small recommendation here, that may make everyone happier here.

It may be worth considering including the `libffi` recipe in your `glibmm` recipe PR to staged-recipes, @scopatz. This way you can make tweaks to both as needed and not be dependent on a quick turnaround for `libffi`. Once the staged-recipes PR gets sorted, feel free to PR the needed changes to `libffi` here.

That will give people more time to review the proposed changes and still allow you to experiment unhindered.

**Comment by scopatz** [comment]
I'll keep that strategy in mind going forward @jakirkham

**Pull request merged**
